In [1]:
import numpy as np
import scipy.optimize as op

In [3]:
g = [[1, 0, 0, -10], [-1, 0, 0, -10], [0, 1, 0, -10], [0, -1, 0, -10], [0, 0, 1, -10], [0, 0, -1, -10]]

In [95]:
N = len(g) + 3
M = np.zeros((N, N))
V = np.zeros((N,))
x0 = 0
y0 = 0
z0 = -12
R = 3
A = 1
B = 1
C = 1
D = 0
E = 0
F = 0
G = -2 * x0
H = -2 * y0
J = -2 * z0
K = x0**2 + y0**2 + z0**2 - R**2

M[0, 0] = 2 * A
M[0, 1] = M[1, 0] = D
M[0, 2] = M[2, 0] = F
M[1, 1] = 2 * B
M[1, 2] = M[2, 1] = E
M[2, 2] = 2 * C

V[0] = -G
V[1] = -H
V[2] = -J
for i in range(3, N):
    V[i] = -g[i - 3][3]
    for j in range(3):
        M[j, i] = M[i, j] = g[i - 3][j]

In [96]:
np.linalg.det(M)

0.0

In [97]:
def fun(x, sign=1):
    f = sign * (A * x[0]**2 + B * x[1]**2 + C * x[2]**2 + D * x[0] * x[1] + E * x[1] * x[2] + F * x[0] * x[2] + \
        G * x[0] + H * x[1] + J * x[2] + K)
    fp = [sign * (2 * A * x[0] + D * x[1] + F * x[2] + G), sign * (2 * B * x[1] + D * x[0] + E * x[2] + H), 
          sign * (2 * C * x[2] + E * x[1] + F * x[0] + J)]
    return f, fp

In [108]:
fun([0, 0, 0], sign=1)

(135, [0, 0, 24])

In [106]:
ans = op.fmin_tnc(fun, [10, 10, 10], args=(1,), bounds=[(-10, 10), (-10, 10), (-10, 10)])
ans

(array([ -9.39725520e-10,  -9.39725520e-10,  -1.00000000e+01]), 5, 0)

In [107]:
fun(ans[0], 1)

(-5.0, [-1.8794510392439179e-09, -1.8794510392439179e-09, 4.0])

In [109]:
a = np.array([1, 2, 3])

In [116]:
a.reshape((3, 1)) + a

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [119]:
b = np.array([[1, 1, 1], [3, 3, 3], [4, 4, 4]])

In [120]:
b+a

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [121]:
np.dot(b, a)

array([ 6, 18, 24])

In [128]:
np.dot(np.array([[1, 2, 3], [4, 5, 6]]), np.transpose(b))

array([[ 6, 18, 24],
       [15, 45, 60]])

In [129]:
a.shape

(3,)

In [130]:
plus = np.array([1, 1, 1, 1])
minus = np.array([-1, -1, -1, -1])
zero = np.array([-1, 0, 1, -1, 1])
def result(a):
    return np.sign(min(a) + max(a))
    

In [135]:
result(zero)

0

In [141]:
a = np.array([1, 2, 3, 4, 5, 6])

In [143]:
a.sum(axis=0)

21

In [12]:
np.finfo(float).resolution

1.0000000000000001e-15

In [4]:
np.__version__

'1.12.1'

In [16]:
a = np.array([-1, -1, -1,  0, 0, 0,  1, 1, 1])
b = np.array([-1,  0,  1, -1, 0, 1, -1, 0, 1])

In [18]:
np.minimum(1, -1)

-1

In [19]:
a = [1, 3, 4]

In [20]:
b = a.copy()

In [21]:
b

[1, 3, 4]

In [22]:
b[1] = 6

In [23]:
b

[1, 6, 4]

In [24]:
a

[1, 3, 4]

In [2]:
class A(dict):
    def __init__(self, **opts):
        dict.__init__(self, opts)
        #for k, v in opts.items():
        #    self[k] = v
    def operate(self, x):
        return x * 2

In [17]:
a = A(a=3, b=4)

In [18]:
def fun(s, x, f):
    return getattr(a, f)(x)

In [20]:
fun(a, 5, 'operate')

10

In [24]:
Z, *A = 'Ar'.split('-')

In [26]:
A

[]

In [10]:
a=[1,2]

In [11]:
a[-1]

2

In [12]:
a=[3]

In [13]:
a[-1]

3